services:
  backend:
    image: month-4
    build:
      context: .
    ports:
      - '3000:3000'
    depends_on:
      - database
  database:
    image: postgres:alpine
    ports:
      - '5432:5433'
    # Can use env_file instead
    # https://docs.docker.com/compose/environment-variables/set-environment-variables/#use-the-env_file-attribute
    # env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
